spring.application.name=notificaciones
server.port=${SERVER_PORT:8083}

spring.rabbitmq.addresses=${RABBITMQ_URL:amqps://evzojucb:iRxjONsFNi5xHvj3imTD5El-i2F1ijjT@gerbil.rmq.cloudamqp.com/evzojucb}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:avlaromaltrain@gmail.com}
spring.mail.password=${MAIL_PASSWORD:iypz sqrk hyob pwyh}

# Propiedades de seguridad obligatorias de Google
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true