spring.application.name=notificaciones

#Puerto distinto para que no choquen los microservicios
server.port=8083

# URL de CloudAMQP(misma que Agendamiento)
spring.rabbitmq.addresses=amqps://evzojucb:iRxjONsFNi5xHvj3imTD5El-i2F1ijjT@gerbil.rmq.cloudamqp.com/evzojucb

# Configuración del servidor de Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=avlaromaltrain@gmail.com
spring.mail.password=iypz sqrk hyob pwyh

# Propiedades de seguridad obligatorias de Google
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true